// Generated by Scripts/generate-rust-shared-memory-abi.sh.
// Source of truth: HALPlugin/Include/MixedAudioSharedMemory.h.
// Do not edit by hand.

pub const MIXED_AUDIO_SHM_MAGIC: u32 = 0x4D415544;
pub const MIXED_AUDIO_SHM_VERSION: u32 = 1;
pub const MIXED_AUDIO_OUTPUT_SAMPLE_RATE: u32 = 48000;
pub const MIXED_AUDIO_OUTPUT_CHANNEL_COUNT: u32 = 2;
pub const MIXED_AUDIO_TARGET_SHARED_FILL_FRAMES: u32 = 2400;
pub const MIXED_AUDIO_HEARTBEAT_STALE_NANOS: u64 = 500000000;
pub const MIXED_AUDIO_PHASE2_MARKER_LEFT: f32 = 0.25;
pub const MIXED_AUDIO_PHASE2_MARKER_RIGHT: f32 = -0.25;
pub const MIXED_AUDIO_SHM_NAME: &str = "/mca.mix.v1";
