#!/bin/sh
set -eu

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
HEADER_PATH="$ROOT_DIR/HALPlugin/Include/MixedAudioSharedMemory.h"
OUTPUT_PATH="$ROOT_DIR/Rust/mixed-audio-engine/src/generated_shared_memory_abi.rs"
MODE="${1:-write}"

fail() {
  printf 'generate rust shared-memory ABI failed: %s\n' "$1" >&2
  exit 1
}

define_value() {
  name="$1"
  value="$(sed -n "s/^#define[[:space:]][[:space:]]*$name[[:space:]][[:space:]]*//p" "$HEADER_PATH" | head -n 1)"
  test "$value" != "" || fail "missing #define $name"
  printf '%s\n' "$value"
}

strip_integer_suffix() {
  printf '%s\n' "$1" | sed 's/[uUlL]*$//'
}

strip_float_suffix() {
  printf '%s\n' "$1" | sed 's/[fF]$//'
}

strip_quotes() {
  printf '%s\n' "$1" | sed 's/^"//; s/"$//'
}

MAGIC="$(strip_integer_suffix "$(define_value MIXED_AUDIO_SHM_MAGIC)")"
ABI_VERSION="$(strip_integer_suffix "$(define_value MIXED_AUDIO_ABI_VERSION)")"
TARGET_FILL_FRAMES="$(strip_integer_suffix "$(define_value MIXED_AUDIO_TARGET_SHARED_FILL_FRAMES)")"
MARKER_LEFT="$(strip_float_suffix "$(define_value MIXED_AUDIO_PHASE2_MARKER_LEFT)")"
MARKER_RIGHT="$(strip_float_suffix "$(define_value MIXED_AUDIO_PHASE2_MARKER_RIGHT)")"
SHM_NAME="$(strip_quotes "$(define_value MIXED_AUDIO_SHM_NAME)")"

TMP_PATH="$(mktemp "${TMPDIR:-/tmp}/mca-rust-abi.XXXXXX")"
cat >"$TMP_PATH" <<EOF
// Generated by Scripts/generate-rust-shared-memory-abi.sh.
// Source of truth: HALPlugin/Include/MixedAudioSharedMemory.h.
// Do not edit by hand.

pub const MIXED_AUDIO_SHM_MAGIC: u32 = $MAGIC;
pub const MIXED_AUDIO_SHM_VERSION: u32 = $ABI_VERSION;
pub const MIXED_AUDIO_TARGET_SHARED_FILL_FRAMES: u32 = $TARGET_FILL_FRAMES;
pub const MIXED_AUDIO_PHASE2_MARKER_LEFT: f32 = $MARKER_LEFT;
pub const MIXED_AUDIO_PHASE2_MARKER_RIGHT: f32 = $MARKER_RIGHT;
pub const MIXED_AUDIO_SHM_NAME: &str = "$SHM_NAME";
EOF

if [ "$MODE" = "--check" ]; then
  if ! cmp -s "$TMP_PATH" "$OUTPUT_PATH"; then
    rm -f "$TMP_PATH"
    fail "$OUTPUT_PATH is out of date; run Scripts/generate-rust-shared-memory-abi.sh"
  fi
  rm -f "$TMP_PATH"
else
  mv "$TMP_PATH" "$OUTPUT_PATH"
fi
